### ISSUE TITLE
Co s texty o stavu různých jurisdikcí?

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#11]
Na titulce webu je zeměkoule, na které se náhodně střídají různé jurisdikce pro certifikaci. Pod nimi vyskakuje text o stavu lokalizace:

> Tento certifikát ještě není úplně lokalizovaný. Přivítáme připomínky k jeho obsahu i použitelnosti – můžete je vkládat na GitHub nebo posílat e-mailem na michal.kuban@motejl.cz. Díky!

Myslel jsem, že ten text se objeví u naší, české jurisdikce. Proto jsme do něj dali kontakty na český lokalizační tým. Takhle se ale text objeví třeba i u Ghany, což není žádoucí. @michalkuban, přehodíme texty zpátky na kontakty z ODI?

**Comment by michalkuban** [comment]
A vadí to tam? Protože já, když kliknu na zeměkouli a vyberu zemi a její distribuci, tak mi to nabídne přihlášení v češtině a pak v rámci procesu tvorby certifikátu si vybírám jazyk, kde člověk ze Zimbabwe,  může přepnout do angličtiny. Obecně mi ten stav alfa-beta trochu vadí, protože s tou jurisdickcí je to matoucí.

**Comment by zoul** [comment]
Mně připadne divné tohle:

![screenshot přepínače](https://cloud.githubusercontent.com/assets/95329/10332455/9b7c73b6-6cdd-11e5-87ff-f1f6c6f4d97c.png)

To vypadá, jako kdybychom měli lokalizaci pro Ghanu na starost my.

**Comment by michalkuban** [comment]
Oh shit. OK. Přehodit to zpátky na ODI. Českou jurisdickci řešíme v češtině, pokud se vybere jiná země, tak by to automaticky mělo přejít do angličtiny a obecně pro ODI.

**Comment by zoul** [comment]
Bohužel ten text nejde změnit podle toho, jestli se zrovna ukazuje naše jurisdikce, nebo cizí. Takže tam buď budou všude naše kontakty, nebo budou všude univerzální kontakty ODI. Dal bych prozatím přednost tomu druhému a možná bychom mohli navrhnout, aby byly kontakty lokalizovatelné? Tedy aby se dal nastavit e-mail (nebo obecně kontakt) pro každou jurisdikci zvlášť a kdyby nebyl nastavený, použije se výchozí kontakt ODI.

**Comment by michalkuban** [comment]
Aha. Tak to je jiná. Určitě druhá možnost, tedy vychozí kontakty na ODI. S příbývajícím počtem lokalizací si to ODI bude muset vyřešit a roztřídit.

**Comment by zoul** [comment]
Změním zpátky na ODI, výhledově pak theodi/open-data-certificate#1290.

**Comment by zoul** [comment]
Změnil jsem v Transifexu zpátky na certificate@theodi.org, na webu se projeví po nejbližším merge (theodi/open-data-certificate#1294).
