### ISSUE TITLE
Filtrování udělených certifikátů podle zemí 

### ISSUE THREAD

**Issue by michalkuban** [Motejl/open-data-certificate#12]
Na hlavní obrazovce je možné kliknout na ZOBRAZIT CERTIFIKÁTY, uživatel se dostane na další obrazovku se seznamy posledně vytvořených certifikátů.  Bylo by dobré zajistit, aby bylo by možné filtrovat certifkáty dle jednotlivých zemí a automaticky ukázat uživateli, kolik jednotlivá země má vygenerovaných certifikátů. Za současného stavu je to nepřehledné.

**Comment by zoul** [comment]
Tohle už je myslím hotové, mrkni na Advanced Search.

**Comment by michalkuban** [comment]
Ok, je to tam. Ale nezobrazují se tam certifikáty ČOI i ČTU. Zřejmě potřebují přepnout do další fáze.

**Comment by zoul** [comment]
Ty jsou totiž zadané na hlavním serveru – tohle je staging server, na kterém se zkouší nové funkce před uvedením na produkční server.
