### ISSUE TITLE
Přeložit statické stránky

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#13]
- [x] [O projektu](http://certificates.theodi.org/cs/about)
  - [x] [How to get a certificate](http://certificates.theodi.org/cs/about/how)
  - [x] [Certificate badge levels](http://certificates.theodi.org/cs/about/badgelevels)
  - [x] [What you need](http://certificates.theodi.org/cs/about/whatyouneed)
- [x] [Podmínky použití](https://certificates.theodi.org/cs/terms)
- [x] [Ochrana osobních údajů](http://certificates.theodi.org/cs/privacy-policy)
- [x] [Prohlášení o cookies](http://certificates.theodi.org/cs/cookie-policy)
- [x] [Napište nám](http://certificates.theodi.org/cs/contact)
- [ ] [FAQ](https://certificates.theodi.org/cs/faq)
- [ ] [Nápověda pro Markdown](http://certificates.theodi.org/cs/markdown) (proč tam vůbec je?)

Ve zdrojáku jsou to soubory v adresáři `app/views/pages`, zatím mně není úplně jasné, jak je technicky přeložit (viz theodi/open-data-certificate#1293).

**Comment by michalkuban** [comment]
Do sekci O projektu (http://staging.certificates.theodi.org/cs/about) bych přeložil, ale současně bych tam doplnil něco o Fondu Otakara Motejla, kdo jsme, co děláme. Tudíž tato sekce nebude doslovná.

**Comment by zoul** [comment]
Souhlas, přesnější je tady mluvit o _lokalizaci_, nikoliv o doslovném překladu. Technicky v tom není rozdíl – ODI nám prostě dá možnost upravit příslušný text. Až se k tomu dostaneme, můžeme se domluvit, co kam nejlíp dát.

**Comment by zoul** [comment]
Ještě zbývá doplnit [text o Fondu Otakara Motejla](https://github.com/Motejl/open-data-certificate/commit/5933e1cc873043731dfe19f86bed74bca229e0b4#commitcomment-14403023), FAQ a nápovědu pro Markdown zatím vynechám.
