### ISSUE TITLE
Filtrování datových sad dle jurisdikce 

### ISSUE THREAD

**Issue by michalkuban** [Motejl/open-data-certificate#17]
Chybí filtrování datových sad dle jurisdikce a současně přeložit slovíčko do češtiny. viz obrázek. 

![image](https://cloud.githubusercontent.com/assets/8858125/11091416/561d633a-887a-11e5-930a-527b2ab3b000.png)

**Comment by michalkuban** [comment]
Překlad: Subscribe to these resiults via RSS a Download...

**Comment by zoul** [comment]
Řetězce týkající se RSS a CSV jsou lokalizované, ale nejspíš jsou ještě někde na cestě z Transifexu na web. (Tedy měly by výhledově naskočit.) Popisek Jurisdiction taktéž. Co myslíš tím, že chybí filtrování sad podle jurisdikce?

**Comment by michalkuban** [comment]
Filtrování dle jurisdikcí asi funguje, ale nezobrazují se současné české certifikáty NKU, ČTU, ČOI. Je možné, že nejsou ve staging verzi. 
Např. https://certificates.theodi.org/en/datasets/26511/certificate

https://certificates.theodi.org/en/datasets/5868/certificate
https://certificates.theodi.org/en/datasets/26074/certificate

**Comment by zoul** [comment]
Přesně tak, staging verze běží nad jinou databází. Tady je [ukázka filtrování na české datasety](https://certificates.theodi.org/cs/datasets?utf8=✓&search=&datahub=&level=&jurisdiction=cz) na produkčním serveru, kde to funguje.

**Comment by michalkuban** [comment]
Super.
