### ISSUE TITLE
Definice „kurátora“

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#2]
V právní části je text „data byla vytvořena přímo poskytovatelem“. V originálu je _curator_, podle právníků existuje v českém prostředí přímo _kurátor_, jen není jasné, jestli je skutečně myšlen _kurátor_ podle české definice.

**Comment by michalkuban** [comment]
Ano, kurátor sedí. Je to tedy osoba na úřadě, která pracuje s konkrétními daty, třeba z odboru školství a dopravy a posílá data koordinatorovi pro zpracování. 

Popis role: 
http://opendata.gov.cz/role:kurator-dat

nebo
Kurátor dat je garantem jemu příslušejících datových sad. Spolupracuje s Koordinátorem otevírání dat na umístění těchto datových sad do publikačního plánu a připravuje je ke zveřejnění. Vykonává následující činnosti:

V rámci vytvoření publikačního plánu Kurátor dat zajišťuje následující činnost:

navrhuje datové sady ke zveřejnění
V rámci zveřejnění konkrétní datové sady v otevřené podobě Kurátor dat zajišťuje následující činnosti:

analyzuje datovou sadu,
připravuje datovou sadu k publikaci.

Jinak jednotlivé role při publikaci otevřených dat s postupy a tvorbou publikačního plánu jsou popsány zde: http://opendata.gov.cz/standardy:vytvoreni-publikacniho-planu

**Comment by zoul** [comment]
Nakonec myslím, že se obejdeme úplně bez toho slova. Jde tam čistě o to, jestli ta data vyrobila nebo sebrala přímo organizace, která je publikuje. (Pokud pokud ne, může to být ošemetné s právy.) Každopádně kdo přesně je v té organizaci vyrobil a kdo je publikuje už není zásadní.
