### ISSUE TITLE
Licencování, autorská a databázová práva

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#4]
V českém právním prostředí není možné se autorských práv vzdát („s výjimkou sui generis DB“, abych citoval právníky), takže celá sekce o vzdání se práv je problematická.

**Comment by zoul** [comment]
Když se podíváte na [zdrojový kód formuláře](https://github.com/zoul/open-data-certificate/blob/czech-translation-fixes/prototype/jurisdictions/certificate.CZ.xml), vypadá to, že bychom na něj měli být schopni tu českou situaci namontovat.

Jde hlavně o prvek question s identifikátorem `dataLicence`, řádek 142. Když na chvilku odhlédnete od aktuálního českého překladu, tak tahle celá otázka by se mohla vztahovat na databázová práva, s možností se jich vzdát. Autorská práva by přišla na řadu až u otázky s identifikátorem `contentRights`, řádek 215. Tam je sice taky možnost se práv vzdát (řádek 267), ale tuhle odpověď bychom mohli prostě vypustit, aplikaci to téměř jistě vadit nebude.

Ve výsledku bychom měli samostatnou otázku na databázová práva s následujícími možnostmi:

```
– CC-BY
– CC-BY-SA
– CC0
– ODC-BY
– ODC-ODBL
– ODC-PDDL
– jiná
– nehodí se
    – nevztahují se
    – vypršela
    – držitel se vzdal
        – PDDL
        – CC0
        – jinak
```

A samostatnou otázku na autorská práva s následujícími možnostmi:

```
– obsah není autorskoprávně chráněn
    – jde o volné dílo?
– ano, jeden držitel
    – CC-BY
    – CC-BY-SA
    – CC0
    – jiná
    – nehodí se
        – na datovou sadu se nevztahují autorská práva
        – autorskoprávní ochrana díla vypršela
        – autor se vzdal ochrany
            – CC0
            – jinak
– ano, více držitelů
    – konkrétní podmínky
```

Dává to smysl, odpovídá to české právní situaci?

**Comment by zoul** [comment]
Po diskuzi s právníky to vypadá jako perspektivní směr. Ještě jsme oddělili autorská práva na databázi jako takovou a autorská práva na díla, která jsou obsahem databáze. Kromě toho jsem celý strom otázek přeorganizoval, když už stejně budeme zasahovat do datového modelu a nemůžeme se držet anglické předlohy. Aktuální verze:

![Rozhodovací strom licencování](https://cloud.githubusercontent.com/assets/95329/8002643/d5f5494c-0b70-11e5-984f-584da786b961.png)

Pokud některé z autorských práv drží víc osob, využije se cesta 2–2–4 nebo 3–1–4.

**Comment by zoul** [comment]
První část práce na novém kódu příslušné části dotazníku je v commitu b9975fc. Co zbývá:
- [x] Doplnit úrovně certifikátu (Raw/Pilot/Standard/Expert)
- [x] Měli bychom u všech licencí dodaných uživatelem přidat otázku, jestli jde o otevřenou licenci?
- [x] Doplnit nápovědné texty

**Comment by LucieStrakova** [comment]
Ještě k překladu: Atriibution překládat jako "Uveďte původ", případně kde se to hodí, tak "uveďte autora a původ" -> nově používaný (správnější) překlad CC ve verzi 4.0 - tj. zachovejme konzistentnost

62 - Uveďte URL dokumentu, který popisuje práva k opětovnému užití této datové sady. Dokument by měl odkazovat na text licence, popsat vaše požadavky na uvádění autora a původu dat, a obsahovat prohlášení o relevantních autorských a databázových právech. Právní prohlášení pomáhá uživatelům pochopit, co všechno s daty mohou a nemohou dělat.

63 - <strong>Měli byste zveřejnit právní prohlášení</strong>, které podrobně popíše autorská a databázová práva spojená s vašimi daty, licenční podmínky a vaše požadavky na uvádění autora a původu díla.

180 - způsob uvádění původu díla

181 - způsob uvádění původu díla

183 - URL pro uvedení původu

184 - URL pro uvedení původu

201 - Je dobrým zvykem uvádět informace o právech ve strojově čitelné podobě, aby uživatelé vašich dat mohli snadno uvést jejich autora a původ.

Díky moc.

**Comment by zoul** [comment]
Můj návrh nápovědných textů. Číslování je podle diagramu výše, pro přehlednost jsem ještě v kurzivě zopakoval samotnou otázku. Soustředil jsem se hlavně na to trojí rozdělení právní ochrany (databázová práva, autorská práva na celou sadu, autorská práva na obsah sady), které mně přijde složité a nápovědyhodné.
1. _Vztahují se na vaši datovou sadu databázová práva?_ Na každou datovou sadu se v českém právním systému dá pohlížet dvojím způsobem, jako na databázi a jako na autorské dílo. V této otázce nás zajímá pohled první: každá databáze, na jejíž sestavení bylo vynaloženo netriviální úsilí, je chráněna databázovými právy.
   1. _Jakým způsobem je licencujete?_ Pokud chcete svou datovou sadu zveřejnit coby otevřená data, musíte mít otevřenou licenci pro její databázová práva.
2. _Vztahují se na datovou sadu autorská práva?_ Na vaši datovou sadu se také můžeme dívat pohledem autorského zákona. Ten se na ni vztahuje potenciálně hned dvakrát: jednak na datovou sadu jako celek, jednak na její obsah. V této otázce nás zajímá první pohled, tedy celá datová sada coby autorské dílo.
   1. (bez nápovědy)
   2. _Jakým způsobem je licencujete?_ Pokud chcete svou datovou sadu zveřejnit coby otevřená data, musíte mít otevřenou licenci pro její autorská práva.
3. _Obsahuje datová sada díla chráněná autorským zákonem?_ Po databázových právech a autorských právech na datovou sadu jako celek nás zajímá ještě třetí možný typ právní ochrany: autorská práva na díla uložená ve vaší datové sadě.

Zbytek bych asi nechal bez nápovědy, pokud se neukáže, že se v tom testeři ztrácejí.

**Comment by LucieSmolks** [comment]
Souhlas, jenom bych změnila "její práva". Rozumím, že je to delší, nicméně ta práva nepřísluší tak úplně té databázi jako jejímu tvůrci.
1. i. ...pro databázová práva, která se na ni vztahují.
2. ii. ...pro autorská práva, která se na ni vztahují.

**Comment by zoul** [comment]
Souhlas, nápovědné texty jsem nasázel do formuláře (3fb2dd1).

**Comment by zoul** [comment]
Ještě jsme chtěli vědět, jestli se u každé licence dodané uživatelem (možnost „jinak“, například cesta 1–1–4) máme ptát, jestli jde o otevřenou licenci. Jestli dobře rozumím tomu, co říkala Sumika, automaticky se předpokládá, že jde o otevřenou licenci. Možná bychom to mohli dát najevo v textech, například změnit _jinak_ na _jinou otevřenou licencí_.

**Comment by zoul** [comment]
Do seznamu licencí k výběru jsem přidal konkrétní čísla verzí, aby bylo jasné, pod jakou CC licencí jsou práva k datové sadě licencovaná, viz commit 7a64976.

**Comment by zoul** [comment]
Snažil jsem se zorientovat v tom, jak funguje systém úrovní (Raw/Pilot/Standard/Expert). Nějaká technická nápověda je v [README u hlavního projektu](https://github.com/theodi/open-data-certificate/blob/staging/README.md#surveyor-extensions).

Jak tomu rozumím, prvek `requirement` funguje pouze jako „hint“, který se zobrazí u dané otázky a napovídá uživateli, jak zvýšit úroveň certifikátu. („Jestli chcete dosáhnout na úroveň Pilot, měli byste data zveřejnit pod takovou a takovou licencí.“) Pro opravdické počítání úrovní slouží atribut `required`, kterým se otázka dá označit jako povinná pro danou úroveň. (Například pokud má certifikát vyšplhat na úroveň Pilot, musí mít zodpovězené všechny otázky s atributem `required` nastaveným na hodnotu `pilot`.) 

V anglické verzi licenčních otázek nebyla žádná otázka označená jako `required` pro konkrétní úroveň, takže licencování momentálně vůbec nepřispívá do systému úrovní (ani v anglické mutaci). To asi není ideální, ale neřešil bych to teď a tady – můžeme se k tomu vrátit později.
