### ISSUE TITLE
Jak přeložit název celého projektu?

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#5]
První otázka celého certifikátu v originálu zní: „What’s this data called?“ Zadaná hodnota se stane názvem celého certifikátu a figuruje dál ve všech možných seznamech. První verze českého překladu je: „Jaký je název vašeho projektu?“ @kubanster navrhuje, jestli bychom nenašli něco lepšího. Prosté „jaký je název vaší datové sady“ mi nepřipadne ideální, protože hned o pár otázek dál může uživatel zaškrtnout, že ve skutečnosti publikuje několik souvisejících datových sad, případně API.

**Comment by michalkuban** [comment]
Navrhuji použít termín "distribuce datové sady", který používáme v metodice ministerstva vnitra. http://opendata.gov.cz/standardy:stupne-otevrenosti

**Comment by zoul** [comment]
Momentálně vůbec nemůžu upravit stávající lokalizaci tohohle řetězce, viz theodi/open-data-certificate#1332. Jakmile se to spraví, navrhuju „Jaký je název vaší datové sady“. Technicky vzato to není úplně správně, ale bojím se, že technicky správnější „distribucí datové sady“ už by zase nebyla moc srozumitelná.

**Comment by zoul** [comment]
Hotovo. Zavírám, ale změna se projeví až později, až se naše změny na Transifexu zanesou do oficiálního repository ODI.
