### ISSUE TITLE
Překlady názvů licencí

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#6]
Je potřeba projít a sjednotit názvy licencí, abychom se synchronizovali s českým překladem CC. Je otázka, co s čísly verzí: Z logiky věci by se hodilo číslo verze uvádět, protože různé verze licencí mají jiné podmínky, ale tím by nám jednak nakynul seznam možností, a jednak ještě CC 4.0 nemá dokončený český překlad. [CC: @LucieStrakova]

**Comment by zoul** [comment]
Sjednotil jsem na „Creative Commons Uveďte autora“ a „Creative Commons Uveďte autora - Zachovejte licenci“ ([podle příručky](http://www.iure.org/sites/default/files/article/downloads/cc_barevne_upravy_7_5.pdf)), viz commit 8853644.

**Comment by LucieSmolks** [comment]
Prosím nepoužívat "Uveďte autora" ale "Uveďte původ". Uveďte autora je prvek dříve používaný, ale je zavádějící, neboť pro splnění podmínek nestačí uvést autora, ale i název díla, zdroj díla a odkaz na licenci. 
Příručka byla zveřejněná bohužel ještě v nefinální verzi, to se omlouváme za matení, lze se nicméně řídit podle stránek creativecommons.cz nebo i http://creativecommons.org/choose/ v české mutaci.

**Comment by zoul** [comment]
Pardon, moje chyba. Psalas mně to, ale nějak jsem to vypustil z hlavy. Opravím.

**Comment by zoul** [comment]
Opraveno.

**Comment by zoul** [comment]
V ODI naše změny zapracovávali ručně a nevím, jestli zaznamenali tuhle změnu. Teď budu čtrnáct dní pryč, ale až se vrátím, ještě se podívám na nový překlad v Trasifexu, jestli jsou názvy licencí správně.

**Comment by zoul** [comment]
Nebyly (_autor_ místo chtěného _původ_), opravil jsem.
