### ISSUE TITLE
Co s automatickou certifikací dat?

### ISSUE THREAD

**Issue by zoul** [Motejl/open-data-certificate#9]
Každý certifikát začíná obrazovkou, která – jestli tomu dobře rozumím – slouží k automatické certifikaci dat:

![úvodní obrazovka certifikačního formuláře](https://cloud.githubusercontent.com/assets/95329/10332048/aa942c0c-6cda-11e5-830d-95111acf3f22.png)

Jedna věc je, že zrovna tahle obrazovka není dobře přeložená nebo je blbě popsaná už v originálu, každopádně není srozumitelná. Druhá věc je, že automatická certifikace je pro české prostředí úplně k ničemu, všichni tam budou chtít zmáčknou čudlík _Skip this_. Co s tím, @michalkuban? Nejlíp asi poprosit ODI, aby umožnili automatickou certifikaci ve vybraných jurisdikcích vypnout? (Snad by byli pro, když jim na ní tolik záleží. Třeba aspoň dočasně.)

**Comment by michalkuban** [comment]
@zoul Souhlasím. Ideálně vypnout a později implentovat až mi budeme za min. půl roku řešit automatickou certifikaci.

**Comment by zoul** [comment]
Nahlásil jsem, theodi/open-data-certificate#1289.

**Comment by zoul** [comment]
Tohle jsme si ještě vyjasnili mailem – automatická certifikace zůstane, ale je potřeba zlepšit text na téhle obrazovce a vyzkoušet automatickou certifikaci s nějakým českým datasetem. Datovou sadou, chci říct :–)

**Comment by zoul** [comment]
Zkoušíme. Zatím se nedaří najít žádný český dataset, který by do formuláře po úvodním kroku něco vyplnil. Co jsme zkoušeli:
- http://data.mfcr.cz/cs/dataset/centralni-registr-administrativnich-budov
- http://linked.opendata.cz/en/dataset/sao-check-actions/resource/49e69f7f-f41a-48ba-a03c-dfdefe31ca55
- http://data.mfcr.cz/cs/dataset/centralni-registr-administrativnich-budov/resource/aa18b138-3e94-4b1e-9356-cf60eec122eb

Já té automatické certifikaci nerozumím a momentálně nemám čas se dívat, jak to přesně funguje, a jestli jsou ta česká URL „v pořádku“, tedy obsahují požadované informace. Pokud ano, může to být rozbité nebo třeba dočasně vypnuté v aplikaci.

**Comment by zoul** [comment]
[Tady](http://linked.opendata.cz/dataset/sao-check-actions) je fungující URL.

**Comment by zoul** [comment]
Dal jsem do toho dialogu trochu pochopitelnější český text, zavírám.
